#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PLAYFIELD_WIDTH 10
#define PLAYFIELD_HEIGHT 20

#define LATERAL_MOVEMENT_DELAY 10
#define LATERAL_MOVEMENT_REPEAT_DELAY 2

#define ROTATION_DELAY 30

#define SOFT_LOCK_DELAY 30
#define ENTRY_DELAY 6

#endif // CONSTANTS_H