#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PLAYFIELD_WIDTH 10
#define PLAYFIELD_HEIGHT 20

#define LATERAL_MOVEMENT_DELAY 10
#define LATERAL_MOVEMENT_REPEAT_DELAY 2

#define ROTATION_DELAY 30

#define SOFT_LOCK_DELAY 20
#define ENTRY_DELAY 6

#define LINE_CLEAR_DELAY 30
#define LINE_CLEAR_FLASH_DELAY 10
#define LINE_CLEAR_DISAPPEAR_DELAY 10
#define LINE_CLEAR_COLLAPSE_DELAY 10

#endif // CONSTANTS_H